### ISSUE TITLE
CSI 1.0 Driver name should be forward domain notation

### ISSUE THREAD

**Issue by saad-ali** [Datera/kubernetes-driver#2]
Per the [CSI spec](https://github.com/container-storage-interface/spec/blob/master/spec.md#getplugininfo) the name of a CSI driver must conform to the following requirements:

```
The name MUST follow domain name notation format (https://tools.ietf.org/html/rfc1035#section-2.3.1).

It SHOULD include the plugin's host company name and the plugin name, to minimize the possibility of collisions.

It MUST be 63 characters or less, beginning and ending with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), dots (.), and alphanumerics between.

This field is REQUIRED.
```

CSI 0.x required reverse domain notation. But [CSI 1.0](https://github.com/container-storage-interface/spec/releases/tag/v1.0.0) dropped the "reverse" part of the requirement. The expectation is that the name will be normal (forward) domain notation.

So instead of `io.datera.csi.dsp` the driver name should be `dsp.csi.datera.io`

**Comment by mattsmithdatera** [comment]
Hey saad, thanks for catching that.  This version of the CSI plugin's yaml files is deprecated and needed to be removed.  We've moved development over to github.com/Datera/datera-csi which also includes the source code for the plugin itself.

I'll get this removed so it won't accidentally be used as a reference.

**Comment by saad-ali** [comment]
Thanks. Could you also submit a PR to https://github.com/kubernetes-csi/docs/pulls to update the link in https://kubernetes-csi.github.io/docs/drivers.html ?
